[tasks.default]
    links = [
        [".gitconfig"],
        [".custom-oh-my-zsh"],
        [".zshrc"],
        [".smartcd_config"],
        [".gitignore_global"],
        [".local/share/umake/ide/spring-tools-suite/STS.ini"],
        [".profile"]
    ]
